project_id = "mfwqlhmxojxbikfhqeaw"

[functions.calculate-route]
verify_jwt = false

[functions.create-pix-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.analyze-route-ai]
verify_jwt = false

[functions.get-route-map]
verify_jwt = false
